version: '2'

services:
    app:
        build: .
        container_name: 'node'
        ports: 
            - '80:80'
        environment:
            - MONGO_HOST=mongo
        links: 
            - mongo

    mongo:
        image: mongo:latest
        hostname: mongo
        ports:
            - '27017:27017'
