version: '2'

services:
    app:
        build: .
        container_name: 'node'
        ports: 
            - '80:80'

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
