version: '3'

services:
    app:
        build: .
        container_name: 'node'
        ports: 
            - '3000:3000'
        environment:
            - MONGO_HOST=mongo
        links: 
            - mongo

    mongo:
        image: mongo:latest
        hostname: mongo
        ports:
            - '27017:27017'
        restart: always
        image: mongo
        volumes:
            - mongo-volume:/data/db

volumes:
    mongo-volume:
        driver: local
